### ISSUE TITLE
Sample app crashes due to unrequested permissions (API 23+)

### ISSUE THREAD

**Issue by espertus** [WindSekirun/NaraeAudioRecorder#10]
I forked the repo and tried running it unchanged on a Pixel 2 running Android 10. The sample app crashed when I clicked on the `Start` button. The log showed that this was because some of the permissions were ungranted. On Marshmallow and later, `ActivityCompat.requestPermissions()` must be called.

**Comment by WindSekirun** [comment]
Sorry, i almost forgot to release version.
Released in 1.3.0. thanks!
