### ISSUE TITLE
Are there anyway to reset recording file and rerecord?

### ISSUE THREAD

**Issue by CyrusCeasar** [WindSekirun/NaraeAudioRecorder#12]
Hello, I want to reset recording file and rerecord to get a better record.  
Is it the only way to reset that deleteing the file just recorded ?

**Comment by WindSekirun** [comment]
I don't understand what your problem. Delete file and call 'create' will reset recording.

**Comment by CyrusCeasar** [comment]
Ok, I got it. Thank u!
